name: DEV - ADS Dallas sales consumer
on:
  push:
    branches: [ development ]
    paths:
     - "ads-dallasSales-consumer/**"
     - ".github/workflows/dev-ads-dallas-sales-consumer.yml"
  workflow_dispatch: # allow manual runs

permissions:
  id-token: write
  contents: write

jobs:
  buildTypescriptApp:
    uses: Signet-sd/esi-devops/.github/workflows/typescriptBuildApp.yml@development
    with:
      environment: dev
      workingDirectory: ads-dallasSales-consumer
      AWSRoleToAssume: arn:aws:iam::481270058004:role/signet-gha-esi-oidc-role
      AWSRoleSessionName: signet-gha-esi-oidc-role
      outputArtifactPath: ./ads-dallasSales-consumer/dist
      outputArtifactUploadName: typescriptApp
      runTests: false
      runSonarScan: false
      sonarProjectProperties: "ads-dallasSales-consumer/sonar-project.properties"
      installCommand: |
        aws codeartifact login --tool npm --repository esi-integration-lib-test --domain signet-esi --domain-owner 872987878890 --region us-east-2
        npm install
      buildCommand: 'npm run build --if-present'
    secrets:
      npmAuthToken: ${{ secrets.yourToken }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  synthDev:
    needs: [buildTypescriptApp]
    uses: Signet-sd/CICD-Templates/.github/workflows/AgnosticCDKSynth.yml@v10.0.0
    with:
      environment: dev
      workingDirectory: ads-dallasSales-consumer/cdk
      AWSRoleToAssume: arn:aws:iam::481270058004:role/signet-gha-esi-oidc-role
      AWSRoleSessionName: signet-gha-esi-oidc-role
      inputArtifactDownloadName: typescriptApp
      inputArtifactPath: ads-dallasSales-consumer/cdk/dist
      installCommand: |
        aws codeartifact login --tool pip --domain signet-common --domain-owner 354008749183 --repository signet-common-pypi --region us-east-2
        pip3 install -r requirements.txt
      synthArgs: -c env=dev
      outputArtifactUploadName: devBuild
    secrets:
      githubToken: ${{ secrets.PULL_REPOSITORY_PAT }}
      githubArtifactToken: ${{ secrets.SIGNET_SD_PACKAGES_READ }}
      orcaSecurityApiToken: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
      orcaProjectKey: ${{ secrets.ORCA_PROJECT_KEY }}

  deployDev:
      needs: [synthDev]
      uses: Signet-sd/CICD-Templates/.github/workflows/cdkDeploy.yml@main
      with:
        environment: dev
        nodeVersion: 20
        deployArgs: -c env=dev
        AWSRoleToAssume: arn:aws:iam::481270058004:role/signet-gha-esi-oidc-role
        AWSRoleSessionName: signet-gha-esi-oidc-role
        inputArtifactDownloadName: devBuild

  synthTest:
    needs: [buildTypescriptApp]
    uses: Signet-sd/CICD-Templates/.github/workflows/AgnosticCDKSynth.yml@v10.0.0
    with:
      environment: test
      workingDirectory: ads-dallasSales-consumer/cdk
      AWSRoleToAssume: arn:aws:iam::611370861527:role/signet-gha-esi-oidc-role
      AWSRoleSessionName: signet-gha-esi-oidc-role
      inputArtifactDownloadName: typescriptApp
      inputArtifactPath: ads-dallasSales-consumer/cdk/dist
      installCommand: |
        aws codeartifact login --tool pip --domain signet-common --domain-owner 354008749183 --repository signet-common-pypi --region us-east-2
        pip3 install -r requirements.txt
      synthArgs: -c env=test
      outputArtifactUploadName: testBuild
    secrets:
      githubToken: ${{ secrets.PULL_REPOSITORY_PAT }}
      githubArtifactToken: ${{ secrets.SIGNET_SD_PACKAGES_READ }}
      orcaSecurityApiToken: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
      orcaProjectKey: ${{ secrets.ORCA_PROJECT_KEY }}

  deployTest:
      needs: [synthTest]
      uses: Signet-sd/CICD-Templates/.github/workflows/cdkDeploy.yml@main
      with:
        environment: test
        nodeVersion: 20
        deployArgs: -c env=test
        AWSRoleToAssume: arn:aws:iam::611370861527:role/signet-gha-esi-oidc-role
        AWSRoleSessionName: signet-gha-esi-oidc-role
        inputArtifactDownloadName: testBuild
