name: STAGE - Common stack (dynamodb)
on:
  push:
    branches: [ release ]
    paths:
     - "common/**"
     - ".github/workflows/stage-ads-common-stack.yml"
  workflow_dispatch: # allow manual runs

permissions:
  id-token: write
  contents: write

jobs:
  synthStage:
    uses: Signet-sd/CICD-Templates/.github/workflows/AgnosticCDKSynth.yml@v10
    with:
      environment: stage
      workingDirectory: common/cdk
      AWSRoleToAssume: arn:aws:iam::343261398662:role/signet-gha-esi-oidc-role
      installCommand: |
        aws codeartifact login --tool pip --domain signet-common --domain-owner 354008749183 --repository signet-common-pypi --region us-east-2
        pip3 install -r requirements.txt
      synthArgs: -c env=stage
      outputArtifactUploadName: stageBuild
    secrets:
      githubToken: ${{ secrets.PULL_REPOSITORY_PAT }}
      githubArtifactToken: ${{ secrets.SIGNET_SD_PACKAGES_READ }}
      orcaSecurityApiToken: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
      orcaProjectKey: ${{ secrets.ORCA_PROJECT_KEY }}

  deployStage:
      needs: [synthStage]
      uses: Signet-sd/CICD-Templates/.github/workflows/cdkDeploy.yml@main
      with:
        environment: stage
        nodeVersion: 20
        deployArgs: -c env=stage
        AWSRoleToAssume: arn:aws:iam::343261398662:role/signet-gha-esi-oidc-role
        inputArtifactDownloadName: stageBuild

  synthProd:
    uses: Signet-sd/CICD-Templates/.github/workflows/AgnosticCDKSynth.yml@v10
    with:
      environment: prod
      workingDirectory: common/cdk
      AWSRoleToAssume: arn:aws:iam::355920665683:role/signet-gha-esi-oidc-role
      installCommand: |
        aws codeartifact login --tool pip --domain signet-common --domain-owner 354008749183 --repository signet-common-pypi --region us-east-2
        pip3 install -r requirements.txt
      synthArgs: -c env=prod
      outputArtifactUploadName: prodBuild
    secrets:
      githubToken: ${{ secrets.PULL_REPOSITORY_PAT }}
      githubArtifactToken: ${{ secrets.SIGNET_SD_PACKAGES_READ }}
      orcaSecurityApiToken: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
      orcaProjectKey: ${{ secrets.ORCA_PROJECT_KEY }}

  deployProd:
      needs: [synthProd]
      uses: Signet-sd/CICD-Templates/.github/workflows/cdkDeploy.yml@main
      with:
        environment: prod
        nodeVersion: 20
        deployArgs: -c env=prod
        AWSRoleToAssume: arn:aws:iam::355920665683:role/signet-gha-esi-oidc-role
        inputArtifactDownloadName: prodBuild